# -*- coding: utf-8 -*-
"""Save Files

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ac6wUIsPlgKZtVqYGaiybY_84pfSqIjx
"""

import openpyxl
from openpyxl.utils import get_column_letter
from datetime import datetime
import os

# Source workbook name
source_workbook_name = "Temp.xlsx"

# Get the current date and time
current_datetime = datetime.now()
datetime_string = current_datetime.strftime("%Y%m%d%H%M")

# Destination workbook name
destination_workbook_name = f"Backup Log - {datetime_string}.xlsx"
save_directory = "Backup Log"

# Create the save directory if it doesn't exist
os.makedirs(save_directory, exist_ok=True)

# Load the source workbook
source_workbook = openpyxl.load_workbook(source_workbook_name, data_only=True)

# Create a new workbook for backup
backup_workbook = openpyxl.Workbook()
default_sheet = backup_workbook.active
backup_workbook.remove(default_sheet)

# Copy values from source workbook to backup workbook
for sheet_name in ["Test1", "Test2", "Test3", "Test4", "Test5"]:
    source_sheet = source_workbook[sheet_name]
    backup_sheet = backup_workbook.create_sheet(title=sheet_name)

    for row in source_sheet.iter_rows(values_only=True):
        backup_sheet.append(row)

# Save the backup workbook
backup_workbook.save(os.path.join(save_directory, destination_workbook_name))

import openpyxl

# Existing workbook name
existing_workbook_name = "Temp.xlsx"

# Load the existing workbook
existing_workbook = openpyxl.load_workbook(existing_workbook_name)

# Remove existing sheets named "Test1" to "Test5"
for sheet_name in ["Test1", "Test2", "Test3", "Test4", "Test5"]:
    if sheet_name in existing_workbook.sheetnames:
        existing_workbook.remove(existing_workbook[sheet_name])

# Create new sheets named "Test1" to "Test5"
for sheet_name in ["Test1", "Test2", "Test3", "Test4", "Test5"]:
    existing_workbook.create_sheet(title=sheet_name)

# Save the modified workbook
existing_workbook.save(existing_workbook_name)

"""# 新增區段"""